GeogridProc: 36
MetgridProc: 36
WrfProc: 361
WrfdaProc: 361
RealProc: 361
WrfStepProcCount: 361

MpiOptions: 
ObDataDir: ./observations
GeogDataDir: not-used
GfsDir: not-used
BeDir: ./covar-matrices-it
RunWPS: false
EnsembleMembers: 10
EnsembleParallelism: 11
AssimilateOnlyInnerDomain: false
AssimilateFirstCycle: true
AssimilateObservations: true
CoresPerNode: 128
