GeogridProc: 361
MetgridProc: 361
WrfProc: 361
WrfdaProc: 50
RealProc: 361


MpiOptions: --prefix /opt/share/comps/gcc-8.3.1/ompi-4.1.4 -bind-to core -x LD_LIBRARY_PATH
ObDataDir: /data/safe/nowcasting/obs
GeogDataDir: /data/unsafe/geog
GfsDir: /data/unsafe/gfs
CovarMatrixesDir: /data/safe/wrfita
CoresPerNode: 48
RunWPS: true
EnsembleMembers: 0
EnsembleParallelism: 1
AssimilateOnlyInnerDomain: false
AssimilateFirstCycle: true
AssimilateObservations: true

PostprocRules:
  wrfout_d03*: $WRFITA_ROOTDIR/scripts/postproc-wrfout.sh $FILE $DOMAIN $INSTANT > postproc-`basename $FILE`.log
  auxhist23_d03*: $WRFITA_ROOTDIR/scripts/postproc-aux.sh $FILE $DOMAIN $INSTANT > postproc-`basename $FILE`.log
  